// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mls.proto

package mls

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Property struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Bathrooms            string   `protobuf:"bytes,2,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	Bedrooms             string   `protobuf:"bytes,3,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
	LandSize             string   `protobuf:"bytes,4,opt,name=land_size,json=landSize,proto3" json:"land_size,omitempty"`
	MlsId                string   `protobuf:"bytes,5,opt,name=mls_id,json=mlsId,proto3" json:"mls_id,omitempty"`
	MlsNumber            string   `protobuf:"bytes,6,opt,name=mls_number,json=mlsNumber,proto3" json:"mls_number,omitempty"`
	MlsUrl               string   `protobuf:"bytes,7,opt,name=mls_url,json=mlsUrl,proto3" json:"mls_url,omitempty"`
	Parking              []string `protobuf:"bytes,8,rep,name=parking,proto3" json:"parking,omitempty"`
	PhotoUrl             []string `protobuf:"bytes,9,rep,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Price                string   `protobuf:"bytes,10,opt,name=price,proto3" json:"price,omitempty"`
	PublicRemarks        string   `protobuf:"bytes,11,opt,name=public_remarks,json=publicRemarks,proto3" json:"public_remarks,omitempty"`
	Stories              string   `protobuf:"bytes,12,opt,name=stories,proto3" json:"stories,omitempty"`
	PropertyType         string   `protobuf:"bytes,13,opt,name=property_type,json=propertyType,proto3" json:"property_type,omitempty"`
	ListTimestamp        string   `protobuf:"bytes,14,opt,name=list_timestamp,json=listTimestamp,proto3" json:"list_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb9af576948d604f, []int{0}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Property) GetBathrooms() string {
	if m != nil {
		return m.Bathrooms
	}
	return ""
}

func (m *Property) GetBedrooms() string {
	if m != nil {
		return m.Bedrooms
	}
	return ""
}

func (m *Property) GetLandSize() string {
	if m != nil {
		return m.LandSize
	}
	return ""
}

func (m *Property) GetMlsId() string {
	if m != nil {
		return m.MlsId
	}
	return ""
}

func (m *Property) GetMlsNumber() string {
	if m != nil {
		return m.MlsNumber
	}
	return ""
}

func (m *Property) GetMlsUrl() string {
	if m != nil {
		return m.MlsUrl
	}
	return ""
}

func (m *Property) GetParking() []string {
	if m != nil {
		return m.Parking
	}
	return nil
}

func (m *Property) GetPhotoUrl() []string {
	if m != nil {
		return m.PhotoUrl
	}
	return nil
}

func (m *Property) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Property) GetPublicRemarks() string {
	if m != nil {
		return m.PublicRemarks
	}
	return ""
}

func (m *Property) GetStories() string {
	if m != nil {
		return m.Stories
	}
	return ""
}

func (m *Property) GetPropertyType() string {
	if m != nil {
		return m.PropertyType
	}
	return ""
}

func (m *Property) GetListTimestamp() string {
	if m != nil {
		return m.ListTimestamp
	}
	return ""
}

type Listings struct {
	Property             []*Property `protobuf:"bytes,1,rep,name=property,proto3" json:"property,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Listings) Reset()         { *m = Listings{} }
func (m *Listings) String() string { return proto.CompactTextString(m) }
func (*Listings) ProtoMessage()    {}
func (*Listings) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb9af576948d604f, []int{1}
}

func (m *Listings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listings.Unmarshal(m, b)
}
func (m *Listings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listings.Marshal(b, m, deterministic)
}
func (m *Listings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listings.Merge(m, src)
}
func (m *Listings) XXX_Size() int {
	return xxx_messageInfo_Listings.Size(m)
}
func (m *Listings) XXX_DiscardUnknown() {
	xxx_messageInfo_Listings.DiscardUnknown(m)
}

var xxx_messageInfo_Listings proto.InternalMessageInfo

func (m *Listings) GetProperty() []*Property {
	if m != nil {
		return m.Property
	}
	return nil
}

type Request struct {
	PropertyId           string   `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb9af576948d604f, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPropertyId() string {
	if m != nil {
		return m.PropertyId
	}
	return ""
}

func init() {
	proto.RegisterType((*Property)(nil), "mls.Property")
	proto.RegisterType((*Listings)(nil), "mls.Listings")
	proto.RegisterType((*Request)(nil), "mls.Request")
}

func init() { proto.RegisterFile("mls.proto", fileDescriptor_fb9af576948d604f) }

var fileDescriptor_fb9af576948d604f = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x92, 0x51, 0xcb, 0xd3, 0x30,
	0x14, 0x86, 0x9d, 0x75, 0x6b, 0x7b, 0xb6, 0x7e, 0x17, 0x41, 0x31, 0x4c, 0xc5, 0x51, 0x11, 0xa6,
	0xc2, 0x2e, 0x26, 0x5e, 0xf8, 0x0b, 0x64, 0xa0, 0x22, 0xdd, 0xbc, 0x2e, 0xed, 0x12, 0xb6, 0xb0,
	0xa4, 0x89, 0x39, 0xa9, 0xb0, 0xfd, 0x1e, 0x7f, 0xa8, 0x24, 0x69, 0xf7, 0x5d, 0x9e, 0xe7, 0x21,
	0x79, 0xdf, 0xe6, 0x14, 0x72, 0x25, 0x71, 0x63, 0xac, 0x76, 0x9a, 0x24, 0x4a, 0x62, 0xf9, 0x2f,
	0x81, 0xec, 0x97, 0xd5, 0x86, 0x5b, 0x77, 0x25, 0x14, 0xd2, 0x86, 0x31, 0xcb, 0x11, 0xe9, 0x64,
	0x35, 0x59, 0xe7, 0xd5, 0x38, 0x92, 0xd7, 0x90, 0xb7, 0x8d, 0x3b, 0x5b, 0xad, 0x15, 0xd2, 0xa7,
	0xc1, 0x3d, 0x02, 0xb2, 0x84, 0xac, 0xe5, 0x2c, 0xca, 0x24, 0xc8, 0xfb, 0x4c, 0x5e, 0x41, 0x2e,
	0x9b, 0x8e, 0xd5, 0x28, 0x6e, 0x9c, 0x3e, 0x8b, 0xd2, 0x83, 0xbd, 0xb8, 0x71, 0xf2, 0x02, 0x66,
	0x4a, 0x62, 0x2d, 0x18, 0x9d, 0x06, 0x33, 0x55, 0x12, 0x77, 0x8c, 0xbc, 0x01, 0xf0, 0xb8, 0xeb,
	0x55, 0xcb, 0x2d, 0x9d, 0xc5, 0x38, 0x25, 0xf1, 0x67, 0x00, 0xe4, 0x25, 0xa4, 0x5e, 0xf7, 0x56,
	0xd2, 0x34, 0x38, 0x7f, 0xc9, 0x6f, 0x2b, 0x7d, 0x7f, 0xd3, 0xd8, 0x8b, 0xe8, 0x4e, 0x34, 0x5b,
	0x25, 0xbe, 0xff, 0x30, 0xfa, 0x16, 0xe6, 0xac, 0x9d, 0x0e, 0x87, 0xf2, 0xe0, 0xb2, 0x00, 0xfc,
	0xb1, 0xe7, 0x30, 0x35, 0x56, 0x1c, 0x39, 0x85, 0x58, 0x22, 0x0c, 0xe4, 0x3d, 0x3c, 0x98, 0xbe,
	0x95, 0xe2, 0x58, 0x5b, 0xae, 0x1a, 0x7b, 0x41, 0x3a, 0x0f, 0xba, 0x88, 0xb4, 0x8a, 0xd0, 0x67,
	0xa2, 0xd3, 0x56, 0x70, 0xa4, 0x8b, 0xf8, 0x66, 0xc3, 0x48, 0xde, 0x41, 0x61, 0x86, 0x97, 0xad,
	0xdd, 0xd5, 0x70, 0x5a, 0x04, 0xbf, 0x18, 0xe1, 0xe1, 0x6a, 0x42, 0x8a, 0x14, 0xe8, 0x6a, 0x27,
	0x14, 0x47, 0xd7, 0x28, 0x43, 0x1f, 0x62, 0x8a, 0xa7, 0x87, 0x11, 0x96, 0x5f, 0x20, 0xfb, 0x2e,
	0xd0, 0x89, 0xee, 0x84, 0xe4, 0x03, 0x64, 0xe3, 0x15, 0x74, 0xb2, 0x4a, 0xd6, 0xf3, 0x6d, 0xb1,
	0xf1, 0x5b, 0x1d, 0xd7, 0x58, 0xdd, 0x75, 0xf9, 0x11, 0xd2, 0x8a, 0xff, 0xe9, 0x39, 0x3a, 0xf2,
	0x16, 0xe6, 0xf7, 0x36, 0x82, 0x0d, 0xfb, 0x85, 0x11, 0xed, 0xd8, 0xf6, 0x2b, 0xc0, 0x0f, 0x89,
	0x7b, 0x6e, 0xff, 0xfa, 0xaf, 0xff, 0x04, 0xf0, 0x8d, 0xbb, 0x21, 0x93, 0x2c, 0x42, 0xc0, 0x70,
	0xd5, 0x32, 0xc6, 0x8d, 0x7d, 0xca, 0x27, 0xed, 0x2c, 0xfc, 0x50, 0x9f, 0xff, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x8d, 0xab, 0x0c, 0x5d, 0x5d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MlsServiceClient is the client API for MlsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MlsServiceClient interface {
	GetListing(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Listings, error)
}

type mlsServiceClient struct {
	cc *grpc.ClientConn
}

func NewMlsServiceClient(cc *grpc.ClientConn) MlsServiceClient {
	return &mlsServiceClient{cc}
}

func (c *mlsServiceClient) GetListing(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Listings, error) {
	out := new(Listings)
	err := c.cc.Invoke(ctx, "/mls.MlsService/GetListing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MlsServiceServer is the server API for MlsService service.
type MlsServiceServer interface {
	GetListing(context.Context, *Request) (*Listings, error)
}

func RegisterMlsServiceServer(s *grpc.Server, srv MlsServiceServer) {
	s.RegisterService(&_MlsService_serviceDesc, srv)
}

func _MlsService_GetListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsServiceServer).GetListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mls.MlsService/GetListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsServiceServer).GetListing(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _MlsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mls.MlsService",
	HandlerType: (*MlsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListing",
			Handler:    _MlsService_GetListing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mls.proto",
}
