// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mls.proto

package mls

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// PriceHistory collects the price change over time of a listing.
type PriceHistory struct {
	Price                int32    `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceHistory) Reset()         { *m = PriceHistory{} }
func (m *PriceHistory) String() string { return proto.CompactTextString(m) }
func (*PriceHistory) ProtoMessage()    {}
func (*PriceHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb9af576948d604f, []int{0}
}

func (m *PriceHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceHistory.Unmarshal(m, b)
}
func (m *PriceHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceHistory.Marshal(b, m, deterministic)
}
func (m *PriceHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceHistory.Merge(m, src)
}
func (m *PriceHistory) XXX_Size() int {
	return xxx_messageInfo_PriceHistory.Size(m)
}
func (m *PriceHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceHistory.DiscardUnknown(m)
}

var xxx_messageInfo_PriceHistory proto.InternalMessageInfo

func (m *PriceHistory) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PriceHistory) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// Property contains the detail information of a MLS listing.
type Property struct {
	Address              string          `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Bathrooms            string          `protobuf:"bytes,2,opt,name=bathrooms,proto3" json:"bathrooms,omitempty"`
	Bedrooms             string          `protobuf:"bytes,3,opt,name=bedrooms,proto3" json:"bedrooms,omitempty"`
	LandSize             string          `protobuf:"bytes,4,opt,name=land_size,json=landSize,proto3" json:"land_size,omitempty"`
	MlsId                string          `protobuf:"bytes,5,opt,name=mls_id,json=mlsId,proto3" json:"mls_id,omitempty"`
	MlsNumber            string          `protobuf:"bytes,6,opt,name=mls_number,json=mlsNumber,proto3" json:"mls_number,omitempty"`
	MlsUrl               string          `protobuf:"bytes,7,opt,name=mls_url,json=mlsUrl,proto3" json:"mls_url,omitempty"`
	Parking              []string        `protobuf:"bytes,8,rep,name=parking,proto3" json:"parking,omitempty"`
	PhotoUrl             []string        `protobuf:"bytes,9,rep,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Price                []*PriceHistory `protobuf:"bytes,10,rep,name=price,proto3" json:"price,omitempty"`
	PublicRemarks        string          `protobuf:"bytes,11,opt,name=public_remarks,json=publicRemarks,proto3" json:"public_remarks,omitempty"`
	Stories              string          `protobuf:"bytes,12,opt,name=stories,proto3" json:"stories,omitempty"`
	PropertyType         string          `protobuf:"bytes,13,opt,name=property_type,json=propertyType,proto3" json:"property_type,omitempty"`
	ListTimestamp        int64           `protobuf:"varint,14,opt,name=list_timestamp,json=listTimestamp,proto3" json:"list_timestamp,omitempty"`
	Source               string          `protobuf:"bytes,15,opt,name=source,proto3" json:"source,omitempty"`
	Latitude             float64         `protobuf:"fixed64,16,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64         `protobuf:"fixed64,17,opt,name=longitude,proto3" json:"longitude,omitempty"`
	City                 string          `protobuf:"bytes,18,opt,name=city,proto3" json:"city,omitempty"`
	State                string          `protobuf:"bytes,19,opt,name=state,proto3" json:"state,omitempty"`
	Zipcode              string          `protobuf:"bytes,20,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb9af576948d604f, []int{1}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Property) GetBathrooms() string {
	if m != nil {
		return m.Bathrooms
	}
	return ""
}

func (m *Property) GetBedrooms() string {
	if m != nil {
		return m.Bedrooms
	}
	return ""
}

func (m *Property) GetLandSize() string {
	if m != nil {
		return m.LandSize
	}
	return ""
}

func (m *Property) GetMlsId() string {
	if m != nil {
		return m.MlsId
	}
	return ""
}

func (m *Property) GetMlsNumber() string {
	if m != nil {
		return m.MlsNumber
	}
	return ""
}

func (m *Property) GetMlsUrl() string {
	if m != nil {
		return m.MlsUrl
	}
	return ""
}

func (m *Property) GetParking() []string {
	if m != nil {
		return m.Parking
	}
	return nil
}

func (m *Property) GetPhotoUrl() []string {
	if m != nil {
		return m.PhotoUrl
	}
	return nil
}

func (m *Property) GetPrice() []*PriceHistory {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Property) GetPublicRemarks() string {
	if m != nil {
		return m.PublicRemarks
	}
	return ""
}

func (m *Property) GetStories() string {
	if m != nil {
		return m.Stories
	}
	return ""
}

func (m *Property) GetPropertyType() string {
	if m != nil {
		return m.PropertyType
	}
	return ""
}

func (m *Property) GetListTimestamp() int64 {
	if m != nil {
		return m.ListTimestamp
	}
	return 0
}

func (m *Property) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Property) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Property) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Property) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Property) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Property) GetZipcode() string {
	if m != nil {
		return m.Zipcode
	}
	return ""
}

// Listings holds all the properties collected from the MLS collectors.
type Listings struct {
	Property             []*Property `protobuf:"bytes,1,rep,name=property,proto3" json:"property,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Listings) Reset()         { *m = Listings{} }
func (m *Listings) String() string { return proto.CompactTextString(m) }
func (*Listings) ProtoMessage()    {}
func (*Listings) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb9af576948d604f, []int{2}
}

func (m *Listings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listings.Unmarshal(m, b)
}
func (m *Listings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listings.Marshal(b, m, deterministic)
}
func (m *Listings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listings.Merge(m, src)
}
func (m *Listings) XXX_Size() int {
	return xxx_messageInfo_Listings.Size(m)
}
func (m *Listings) XXX_DiscardUnknown() {
	xxx_messageInfo_Listings.DiscardUnknown(m)
}

var xxx_messageInfo_Listings proto.InternalMessageInfo

func (m *Listings) GetProperty() []*Property {
	if m != nil {
		return m.Property
	}
	return nil
}

// Request defines the parameter for the gRPC service GetListing.
type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb9af576948d604f, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PriceHistory)(nil), "mls.PriceHistory")
	proto.RegisterType((*Property)(nil), "mls.Property")
	proto.RegisterType((*Listings)(nil), "mls.Listings")
	proto.RegisterType((*Request)(nil), "mls.Request")
}

func init() { proto.RegisterFile("mls.proto", fileDescriptor_fb9af576948d604f) }

var fileDescriptor_fb9af576948d604f = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x53, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x25, 0xec, 0x57, 0x32, 0xdd, 0x2d, 0xd4, 0x14, 0xb0, 0x0a, 0x48, 0xab, 0x45, 0x88, 0x45,
	0x48, 0x3d, 0x14, 0x71, 0xe0, 0xca, 0x05, 0x90, 0x00, 0x55, 0x69, 0x39, 0x47, 0xf9, 0xb0, 0xb6,
	0x56, 0xed, 0xd8, 0x78, 0x1c, 0xa4, 0xec, 0x7f, 0xe4, 0x3f, 0x21, 0x8f, 0x93, 0x5d, 0x6e, 0x79,
	0xef, 0x65, 0xde, 0xcc, 0xbc, 0x49, 0x20, 0xd3, 0x0a, 0x2f, 0xad, 0x33, 0xde, 0xb0, 0x89, 0x56,
	0xb8, 0xf9, 0x0c, 0xcb, 0x6b, 0x27, 0x6b, 0xf1, 0x55, 0xa2, 0x37, 0xae, 0x67, 0xe7, 0x30, 0xb3,
	0x01, 0xf3, 0x64, 0x9d, 0x6c, 0x67, 0x79, 0x04, 0xec, 0x25, 0x64, 0x5e, 0x6a, 0x81, 0xbe, 0xd4,
	0x96, 0x3f, 0x5c, 0x27, 0xdb, 0x49, 0x7e, 0x24, 0x36, 0x7f, 0xa7, 0x90, 0x5e, 0x3b, 0x63, 0x85,
	0xf3, 0x3d, 0xe3, 0xb0, 0x28, 0x9b, 0xc6, 0x09, 0x44, 0xb2, 0xc8, 0xf2, 0x11, 0x06, 0x93, 0xaa,
	0xf4, 0x77, 0xce, 0x18, 0x8d, 0x64, 0x92, 0xe5, 0x47, 0x82, 0x5d, 0x40, 0x5a, 0x89, 0x26, 0x8a,
	0x13, 0x12, 0x0f, 0x98, 0xbd, 0x80, 0x4c, 0x95, 0x6d, 0x53, 0xa0, 0xdc, 0x0b, 0x3e, 0x8d, 0x62,
	0x20, 0x6e, 0xe4, 0x5e, 0xb0, 0xa7, 0x30, 0xd7, 0x0a, 0x0b, 0xd9, 0xf0, 0x19, 0x29, 0x33, 0xad,
	0xf0, 0x5b, 0xc3, 0x5e, 0x01, 0x04, 0xba, 0xed, 0x74, 0x25, 0x1c, 0x9f, 0xc7, 0x76, 0x5a, 0xe1,
	0x4f, 0x22, 0xd8, 0x73, 0x58, 0x04, 0xb9, 0x73, 0x8a, 0x2f, 0x48, 0x0b, 0x26, 0xbf, 0x9c, 0x0a,
	0xf3, 0xdb, 0xd2, 0xdd, 0xcb, 0x76, 0xc7, 0xd3, 0xf5, 0x24, 0xcc, 0x3f, 0xc0, 0x30, 0x85, 0xbd,
	0x33, 0xde, 0x50, 0x51, 0x46, 0x5a, 0x4a, 0x44, 0x28, 0x7b, 0x3b, 0xe6, 0x06, 0xeb, 0xc9, 0xf6,
	0xe4, 0xea, 0xec, 0x32, 0xe4, 0xfc, 0x7f, 0xb2, 0x63, 0x94, 0x6f, 0xe0, 0xd4, 0x76, 0x95, 0x92,
	0x75, 0xe1, 0x84, 0x2e, 0xdd, 0x3d, 0xf2, 0x13, 0xea, 0xbf, 0x8a, 0x6c, 0x1e, 0xc9, 0x30, 0x46,
	0x28, 0x93, 0x02, 0xf9, 0x32, 0xc6, 0x38, 0x40, 0xf6, 0x1a, 0x56, 0x76, 0x08, 0xbb, 0xf0, 0xbd,
	0x15, 0x7c, 0x45, 0xfa, 0x72, 0x24, 0x6f, 0x7b, 0x4b, 0x5d, 0x94, 0x44, 0x5f, 0x1c, 0xaf, 0x76,
	0x4a, 0x57, 0x5b, 0x05, 0xf6, 0x76, 0x24, 0xd9, 0x33, 0x98, 0xa3, 0xe9, 0x5c, 0x2d, 0xf8, 0xa3,
	0x18, 0x42, 0x44, 0xe1, 0x18, 0xaa, 0xf4, 0xd2, 0x77, 0x8d, 0xe0, 0x8f, 0xd7, 0xc9, 0x36, 0xc9,
	0x0f, 0x38, 0x9c, 0x51, 0x99, 0x76, 0x17, 0xc5, 0x33, 0x12, 0x8f, 0x04, 0x63, 0x30, 0xad, 0xa5,
	0xef, 0x39, 0x23, 0x3f, 0x7a, 0x0e, 0xdf, 0x14, 0xfa, 0xd2, 0x0b, 0xfe, 0x24, 0x1e, 0x88, 0x40,
	0xd8, 0x70, 0x2f, 0x6d, 0x6d, 0x1a, 0xc1, 0xcf, 0xe3, 0x86, 0x03, 0xdc, 0x7c, 0x84, 0xf4, 0xbb,
	0x44, 0x2f, 0xdb, 0x1d, 0xb2, 0x77, 0x90, 0x8e, 0x8b, 0xf1, 0x84, 0xa2, 0x5d, 0x0d, 0xd1, 0x46,
	0x32, 0x3f, 0xc8, 0x9b, 0x0c, 0x16, 0xb9, 0xf8, 0xdd, 0x09, 0xf4, 0x57, 0x9f, 0x00, 0x7e, 0x28,
	0xbc, 0x11, 0xee, 0x4f, 0x88, 0xfc, 0x3d, 0xc0, 0x17, 0xe1, 0x07, 0x4b, 0xb6, 0xa4, 0xfa, 0xe1,
	0xcd, 0x8b, 0xe8, 0x36, 0xb6, 0xdb, 0x3c, 0xa8, 0xe6, 0xf4, 0x73, 0x7c, 0xf8, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x4e, 0x73, 0x81, 0x2b, 0x29, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MlsServiceClient is the client API for MlsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MlsServiceClient interface {
	GetListing(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Listings, error)
}

type mlsServiceClient struct {
	cc *grpc.ClientConn
}

func NewMlsServiceClient(cc *grpc.ClientConn) MlsServiceClient {
	return &mlsServiceClient{cc}
}

func (c *mlsServiceClient) GetListing(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Listings, error) {
	out := new(Listings)
	err := c.cc.Invoke(ctx, "/mls.MlsService/GetListing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MlsServiceServer is the server API for MlsService service.
type MlsServiceServer interface {
	GetListing(context.Context, *Request) (*Listings, error)
}

func RegisterMlsServiceServer(s *grpc.Server, srv MlsServiceServer) {
	s.RegisterService(&_MlsService_serviceDesc, srv)
}

func _MlsService_GetListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MlsServiceServer).GetListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mls.MlsService/GetListing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MlsServiceServer).GetListing(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _MlsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mls.MlsService",
	HandlerType: (*MlsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListing",
			Handler:    _MlsService_GetListing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mls.proto",
}
